
package com.jbossnotebook.webserviceclient;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "MathService", targetNamespace = "http://www.jbossnotebook.com/", wsdlLocation = "http://localhost:8080/WebServiceExampleWeb/MathService?wsdl")
public class MathService
    extends Service
{

    private final static URL MATHSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.jbossnotebook.webserviceclient.MathService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.jbossnotebook.webserviceclient.MathService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8080/WebServiceExampleWeb/MathService?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/WebServiceExampleWeb/MathService?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        MATHSERVICE_WSDL_LOCATION = url;
    }

    public MathService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MathService() {
        super(MATHSERVICE_WSDL_LOCATION, new QName("http://www.jbossnotebook.com/", "MathService"));
    }

    /**
     * 
     * @return
     *     returns MathWebService
     */
    @WebEndpoint(name = "MathWebServicePort")
    public MathWebService getMathWebServicePort() {
        return super.getPort(new QName("http://www.jbossnotebook.com/", "MathWebServicePort"), MathWebService.class);
    }

}
