
package com.jbossnotebook.webserviceclient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "MathWebService", targetNamespace = "http://www.jbossnotebook.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface MathWebService {


    /**
     * 
     * @param second
     * @param first
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(name = "result", partName = "result")
    public double addDouble(
        @WebParam(name = "first", partName = "first")
        double first,
        @WebParam(name = "second", partName = "second")
        double second);

}
